### ISSUE TITLE
Issue to flag the fact that we think our "narrow" coding options are problematic

### ISSUE THREAD

**Issue by ekothe** [ropenscilabs/gendercoder#11]
Our "narrow" coding dictionary makes opinionated choices about some responses that we want to acknowledge are potentially problematic. 

In particular, 
- Intersex is recoded as "Other"
- Responses where people indicate they are trans* _and_ indicate their presenting gender are recoded as the presenting gender (e.g. "Male to Female" is recoded as Female)

We wish to acknowledge that this may not reflect how some individuals would classify themselves when given these categories and in some contexts may make systematic errors. 

The broad coding dictionary attempts to avoid these issues as much as possible - however users can provide a custom dictionary to add to or overwrite our coding decisions if they feel this is more appropriate. 

We welcome PR to update the inbuilt dictionary where desired responses are missing.

**Comment by rhydwyn** [comment]
Text updated in zzz.R
