### ISSUE TITLE
should "I am XXX" resolve to "XXX"

### ISSUE THREAD

**Issue by ellisp** [ropenscilabs/gendercoder#34]
The example  in the readme currently has "I am male" becoming an NA for narrow_gender and "I am male" for broad_gender. If this is a pattern people actually use, wouldn't it be better if "^I am " (and any similar patterns)were deleted before matching to the dictionary so this resolved to "male", "I am nb" resolves to "sex and gender diverse", etc?

**Comment by ekothe** [comment]
This is a real response - so it is certainly something that we expect to observe. My concern is that some people provide responses in the format "I was assigned female at birth, I am male" (should be coded male) or "I am sexually male, but identify as female" (should be coded female). 

This is similar to a question @Matherion asked on Twitter about why we don't use regex, so if people can see a "safe" way to code responses of this type I'd be very interested.

**Comment by ellisp** [comment]
Hmm, it would inevitably be a bit ad hoc but one could have a "fuzzy" option that searches first for "identify as XXX", then for "I am YYY". If I have any ideas I will do a PR (and won't be offended if it's rejected).

**Comment by Lingtax** [comment]
Do we have a corpus of examples of this type, Emily? If we can at least get a sample of the problem space it should make it easier to advance this.

**Comment by ekothe** [comment]
The included sample data set has some examples of this type - although I know we do get more when purposively sampling more gender diverse participants. I wonder if @debruine would have any additional responses in this format that would be useful for this problem. I know that Lisa has recently collected some data in this format.

**Comment by ekothe** [comment]
See further discussion in #37 - I'm closing this to reduce duplication.
