### ISSUE TITLE
Make a shiny app

### ISSUE THREAD

**Issue by Lingtax** [ropenscilabs/gendercoder#38]
We know there are people who are still wedded to their GUI stats software, and asking them to switch to R is a barrier to them adopting this. I'm too lazy and incompetent to rewrite this for STATA / SPSS, but `haven` and `shiny` already exist. 

Let's make a shiny app that reads the data, and at least does a basic application of the core function (without custom dictionaries) to a new variable and saves it back in the original format.

**Comment by ekothe** [comment]
Are you a mind reader? This was in the issue tracker in my head

**Comment by Lingtax** [comment]
Started  development here: 
https://github.com/Lingtax/gendercoder-app/
